### ISSUE TITLE
GPG command not found

### ISSUE THREAD

**Issue by Grokzen** [drduh/pwd.sh#1]
When executing the script it looks for gpg in a folder that gpg is not installed in by default (on ubuntu 14.04) It is hardcoded to look in `/usr/local/bin/gpg` but default it is installed in `/usr/bin/gpg`. I either have to symlink it to make it work or change the script to look in the correct folder.

Possible solutions, look in more places that it might exist or locate the script with `which gpg` to make it dynamic.

**Comment by espenfjo** [comment]
Use '/usr/bin/env gpg'

**Comment by drduh** [comment]
I've decided to go with *which*. Thanks!

**Comment by gonzalo-bulnes** [comment]
I was giving a try to `gpg="/usr/bin/env gpg"` (which I think is meant to be used in case like this one and at least does work both in OS X and Ubuntu). It does work as I said, but does produce the following warning: 

```bash
./pwd.sh
# => ./pwd.sh: line 177: [: /usr/bin/env: binary operator expected
```

Because of the whitespace in `"/usr/bin/env gpg"`, in line 177 `${gpg}` does produce more arguments that `[]` did expect. (For example, `"/usr/bin/gpg"` does not produce any error - in Ubuntu.)

I tried using single and double quotes, I also tried escaping the whitespace but the issue goes beyond my knowledge of bash variables and operators... any idea?
