### ISSUE TITLE
Final entry can't be removed

### ISSUE THREAD

**Issue by xfra35** [drduh/pwd.sh#28]
Hi,

Thanks for sharing this useful piece of code!

It seems there's a small bug that prevent deletion where there's only one entry remaining.

See:

```bash
./pwd.sh w user1 9
./pwd.sh w user2 9
./pwd.sh w user3 9
./pwd.sh r all
# MIcA4iieW user1
# fi+ALzJvT user2
# GZvLkTX4+ user3
```

```bash
./pwd.sh d user1
./pwd.sh d user2
./pwd.sh d user3
# Error: Write to safe failed
./pwd.sh r all
# GZvLkTX4+ user3
```

I guess that's not a problem for most of users as their safe contains multiple entries, but it is one for new users who want to play with the script and don't understand why the deletion can't work.

**Comment by drduh** [comment]
This is because blank lines are stripped before encrypting, so no input is being passed when the last entry is removed. One solution is to append a modification time so at least some data gets encrypted. Perhaps something like this:

On L9: `$(command -v grep) -v -E` (have to check flag compatibility on BSD and Linux)
On L139: `( ${filter} "^[[:space:]]*$|^mtime:\d+$" ; echo mtime:$(date +%s) ) | \`

Let me know what you think.

**Comment by drduh** [comment]
Tested on OS X 10.11, Debian 8 and OpenBSD 5.9.

Let me know if this works for you, and thanks for the report.

**Comment by xfra35** [comment]
That works great. Thanks for fixing it quickly :+1: 

As a side note, I think it would be more accurate to rename "Decryption failed" into "No password found".
